version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gas-fee-estimator
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gas-fee-estimator
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
